// src/components/Footer.tsx
import { GithubLogo, LinkedinLogo } from "@phosphor-icons/react";

export default function Footer() {
    return (
        <footer className="m-0 p-0 bg-richBlackFogra text-ghostWhite">
            
            <div className="flex items-center justify-center p-8">
                <img id="line" src="/line.svg" alt="line" />
            </div>
            <div className="flex items-center justify-center pb-4 pt-2 text-xl"> 
                <a href="mailto:lucasl22l@proton.me" className="transition-color hover:text-orangeRedCrayole duration-200">
                    <span className="link link-underline link-underline-black">
                        lucasl22l@proton.me
                    </span>
                </a>
            </div>
            <div className="flex items-center justify-center">
                <a href="https://www.linkedin.com/in/l22l/" target="_blank" rel="noreferrer" className="px-2.5">
                   <LinkedinLogo size={36} color="#F7F7FF" weight="fill"/>
                </a>
                <a href="https://github.com/luycaslima" target="_blank" rel="noreferrer" className="px-2.5">
                    <GithubLogo size={36} color="#F7F7FF" weight="fill"/>
                </a>
            </div>
        
            <div className="text-center p-6 text-sm">
                <span>2023. Developed, Pixel art by Lucas Lima.</span>
            </div>
        </footer>
    )
}

// src/components/Footer.vue
<template>
  <footer class="content">
  <div class="media">
    <table>
       <tr>
        <td><img id="line" src="../assets/line.svg" alt="line"></td>
      </tr>
      <tr>
      <div id="buttons">
        <a href="https://github.com/luycaslima" target="_blank"><img src="../assets/social/github.svg" alt="github" /></a>
        <a href="https://www.instagram.com/luycaslima/" target="_blank"><img src="../assets/social/instagram.svg" alt="instagram" /></a>
        <a href="https://github.com/luycaslima" target="_blank"><img src="../assets/social/twitter.svg" alt="twitter" /></a> 
      </div>
      
      </tr>
    </table>   
    <!-- 2017 - 2020 Lucas Lima -->
  </div>
   
  </footer>
  
</template>

<script>


export default {
  name: "Footer",
  components: {
  }
};
</script>

<style scoped>
#line {
  justify-content: center;
  margin: 20px 0px 20px 10px;
}
#buttons {
  position: relative;
  display: flex;
  justify-content: center;
}
#buttons a{
  padding: 0 15px;
}
#buttons img{
  width: 110%;
  height: 110%;
}
.content {
  background-image: url("../assets/background_footer_logo.svg");
  background-repeat: no-repeat;
  background-position: bottom left;
  position: absolute;
  padding: 30px;
  left: 0;
  bottom: 0;
  width: 100%;
  color: white;
  text-align: center;
}
.media{
  
  display: flex;
  justify-content: center;
}


</style>
